### ISSUE TITLE
Payment complete page

### ISSUE THREAD

**Issue by sgmlguru** [sgmlguru/MUK-reg#11]
When the payment is complete and we've fetched the user info from Paypal, we use this to generate a thank-you page with the information and save the temp XML to a user XML file (among other registered delegates).

* Generates a demojam voting code and store that.
* Initiates the PDF generation and email to the user.
* Moves the temp XML file to the appropriate registration type collection.

**Comment by AndrewSales** [comment]
Include return link to the main site (v minor)?

**Comment by sgmlguru** [comment]
Demojam code will be generated by either a different app or additional functionality created later.

**Comment by sgmlguru** [comment]
Added return link to MUK web page. Closing this.
