### ISSUE TITLE
Oops exception

### ISSUE THREAD

**Issue by Gertone** [sgmlguru/MUK-reg#34]
Request Resolution Failure
SOURCE res:/exist/rest/db/apps/MUK-reg/xq/thanks.xquery as IBinaryStreamRepresentation

An unhandled exception occurred whilst processing the request. 

at
http://localhost:8080/exist/rest/db/apps/MUK-reg/xq/thanks.xquery?tmp-file=/db/MUK-data/sandbox/tmp/CFnFstr-tmp.xml

**Comment by sgmlguru** [comment]
Shit. That's a permissions thing, I believe.

**Comment by Gertone** [comment]
nono, ignore the message, NetKernel is running on my port 8080
so this is resourcing issue
it just indicates that you are relaying the thankyou to the port 8080 on the local computer not the server

the issue is in the url:
http://localhost:8080/exist/rest/db/apps/...

**Comment by sgmlguru** [comment]
I should have read the message...

Of course. I forgot to set up that bit.

**Comment by sgmlguru** [comment]
OK, should be fixed now.

**Comment by sgmlguru** [comment]
Geert, can you confirm that this is fixed now?

**Comment by Gertone** [comment]
seems fixed. Registration process goes well up to the point of receiving the invoice
